// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
window.wailsbindings = {"main":{"App":{"Clicks":{"name":"main.App.Clicks","outputs":[{"type":"string"}]},"ClicksPerSecond":{"name":"main.App.ClicksPerSecond","outputs":[{"type":"string"}]},"SetDelay":{"name":"main.App.SetDelay","inputs":[{"type":"string"}]}}}};
const go = {
  "main": {
    "App": {
      /**
       * Clicks
       * @returns {Promise<string>}  - Go Type: string
       */
      "Clicks": () => {
        return window.go.main.App.Clicks();
      },
      /**
       * ClicksPerSecond
       * @returns {Promise<string>}  - Go Type: string
       */
      "ClicksPerSecond": () => {
        return window.go.main.App.ClicksPerSecond();
      },
      /**
       * SetDelay
       * @param {string} arg1 - Go Type: string
       * @returns {Promise<void>} 
       */
      "SetDelay": (arg1) => {
        return window.go.main.App.SetDelay(arg1);
      },
    },
  },

};
export default go;
